# Generated by Django 3.1.7 on 2021-08-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'pizza',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pizzas.pizza')),
            ],
            options={
                'verbose_name_plural': 'topping',
            },
        ),
    ]
