# Generated by Django 3.1.7 on 2021-09-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60, unique=True)),
                ('id_checked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField(default='2000-01-01')),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TAG',
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=60, unique=True)),
                ('id_checked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField(default='2000-01-01')),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TOPIC',
                'ordering': ('-date_modified',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('text', models.TextField()),
                ('id_checked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField(default='2000-01-01')),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blogs.tag')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blogs.topic')),
            ],
            options={
                'verbose_name_plural': 'POST',
                'ordering': ('-date_modified',),
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('id_checked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField(default='2000-01-01')),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blogs.post')),
            ],
            options={
                'verbose_name_plural': 'ENTRY',
                'ordering': ('-date_modified',),
            },
        ),
    ]
