# Generated by Django 3.1.7 on 2021-09-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-date_modified',), 'verbose_name': 'ENTRY', 'verbose_name_plural': 'ENTRY'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_modified',), 'verbose_name': 'POST', 'verbose_name_plural': 'POST'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag',), 'verbose_name': 'TAG', 'verbose_name_plural': 'TAG'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-date_modified',), 'verbose_name': 'TOPIC', 'verbose_name_plural': 'TOPIC'},
        ),
    ]
