# Generated by Django 3.1.7 on 2021-09-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0004_auto_20210906_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='id_checked',
            new_name='is_checked',
        ),
    ]
