# Generated by Django 3.1.7 on 2021-09-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0005_auto_20210907_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='id_checked',
            new_name='is_checked',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id_checked',
            new_name='is_checked',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='id_checked',
            new_name='is_checked',
        ),
    ]
