# Generated by Django 3.2 on 2021-09-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0007_auto_20210911_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_beg',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_beg',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_beg',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_beg',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
