# Generated by Django 3.1.7 on 2021-09-19 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0009_auto_20210918_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='date_beg',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
