# Generated by Django 3.1.7 on 2021-09-19 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0010_auto_20210919_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_beg',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_beg',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_beg',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
