# Generated by Django 3.1.7 on 2021-09-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H2H_server2verfahren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=60, unique=True)),
                ('verfahren', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'H2H_SERVER2VERFAHREN',
                'verbose_name_plural': 'H2H_SERVER2VERFAHREN',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'SERVER',
                'verbose_name_plural': 'SERVER',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Verfahren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verfahren', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'VERFAHREN',
                'verbose_name_plural': 'VERFAHREN',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='T2T_server2verfahren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_server.server')),
                ('verfahren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_server.verfahren')),
            ],
            options={
                'verbose_name': 'T2T_SERVER2VERFAHREN',
                'verbose_name_plural': 'T2T_SERVER2VERFAHREN',
                'ordering': ('id',),
            },
        ),
    ]
