# Generated by Django 3.2.6 on 2021-09-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='verfahren',
            old_name='verfahren',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='h2h_server2verfahren',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='t2t_server2verfahren',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='verfahren',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
