# Generated by Django 3.1.7 on 2021-09-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0002_auto_20210911_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h2h_server2verfahren',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='t2t_server2verfahren',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='verfahren',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
