# Generated by Django 3.2 on 2021-08-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField(default='2000-01-01')),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ip',
                'verbose_name_plural': 'Ipp',
                'ordering': ['id', 'ip'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=32, unique=True)),
                ('model', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField(default='2000-01-01')),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Server',
                'ordering': ['id', 'server'],
            },
        ),
        migrations.CreateModel(
            name='Z_server2ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField(default='2001-01-01')),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('t2t_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_core_server.ip', verbose_name='Ip')),
                ('t2t_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_core_server.server', verbose_name='Server')),
            ],
            options={
                'verbose_name': 'Z_server2ip',
                'verbose_name_plural': 'Z_server2ip',
                'ordering': ['id', 't2t_server', 't2t_ip'],
            },
        ),
    ]
