# Generated by Django 3.2 on 2021-08-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'ordering': ['id', 'ip'], 'verbose_name': 'Ip', 'verbose_name_plural': 'Ip'},
        ),
    ]
