# Generated by Django 3.2 on 2021-04-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zrolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(max_length=120)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rolle',
            },
        ),
        migrations.CreateModel(
            name='Zmitarbeiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=120)),
                ('vorname', models.CharField(max_length=120)),
                ('geburtstag', models.DateField(blank=True, null=True)),
                ('bild', models.ImageField(blank=True, null=True, upload_to='images')),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('rollen', models.ManyToManyField(blank=True, to='app_org.Zrolle')),
            ],
            options={
                'verbose_name_plural': 'Mitarbeiter',
                'unique_together': {('nachname', 'vorname', 'geburtstag')},
            },
        ),
    ]
