# Generated by Django 3.1.7 on 2021-04-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zverfahren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verfahren', models.CharField(max_length=120)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Verfahren',
            },
        ),
        migrations.AddField(
            model_name='zmitarbeiter',
            name='verfahren',
            field=models.ManyToManyField(blank=True, to='app_org.Zverfahren'),
        ),
    ]
