# Generated by Django 3.1.7 on 2021-04-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_org', '0002_auto_20210425_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zt2t_ma_ro_ve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('t2t_mitarbeiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_org.zmitarbeiter', verbose_name='Mitarbeiter')),
                ('t2t_rolle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_org.zrolle', verbose_name='Rolle')),
                ('t2t_verfahren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_org.zverfahren', verbose_name='Verfahren')),
            ],
            options={
                'verbose_name_plural': 't2t_ma_ro_ve',
            },
        ),
    ]
