# Generated by Django 3.1.7 on 2021-05-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_org', '0002_server_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
