# Generated by Django 3.1.7 on 2021-05-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_org', '0003_server_hostname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server_hostname',
            options={'ordering': ['name'], 'verbose_name': 'server_hostname', 'verbose_name_plural': 'server_hostname'},
        ),
        migrations.AlterModelOptions(
            name='server_uuid',
            options={'ordering': ['uuid'], 'verbose_name': 'server_uuid', 'verbose_name_plural': 'server_uuid'},
        ),
        migrations.CreateModel(
            name='Zt2t_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('t2t_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_org.server_hostname', verbose_name='Server_hostname')),
                ('t2t_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_org.server_uuid', verbose_name='uuid')),
            ],
            options={
                'verbose_name': 'Zt2t_server',
                'verbose_name_plural': 'Zt2t_server',
                'ordering': ['t2t_uuid'],
            },
        ),
    ]
