# Generated by Django 3.1.3 on 2021-04-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='geb',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
