# Generated by Django 3.1.3 on 2021-04-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0003_auto_20210410_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_end',
            field=models.DateField(default='2099-12-31'),
        ),
    ]
