# Generated by Django 3.1.3 on 2021-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0005_rolle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolle',
            name='beschreibung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolle',
            name='date_end',
            field=models.DateField(default='2099-12-31'),
        ),
    ]
