# Generated by Django 3.1.3 on 2021-04-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0014_itskobjekte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sap_system_landschaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ItskObjekte',
            new_name='Infra_umgebung',
        ),
        migrations.RenameModel(
            old_name='InfraUmgebung',
            new_name='Inventar_art',
        ),
        migrations.RenameModel(
            old_name='SapSystemLandschaft',
            new_name='Itsk_objekte',
        ),
    ]
