# Generated by Django 3.1.3 on 2021-04-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0015_auto_20210417_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('inventar_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_test.inventar_art')),
            ],
        ),
    ]
