# Generated by Django 3.1.7 on 2021-04-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitarbeiter2',
            name='nname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mitarbeiter2',
            name='vname',
            field=models.CharField(max_length=120),
        ),
    ]
