# Generated by Django 3.1.7 on 2021-04-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sap', '0002_auto_20210407_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter2',
            name='handy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
