# Generated by Django 3.1.7 on 2021-04-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infra_umgebung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Infra_umgebung',
                'verbose_name_plural': 'Infra_umgebung',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventar_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventar_art',
                'verbose_name_plural': 'Inventar_art',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Itsk_objekte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Itsk_objekte',
                'verbose_name_plural': 'Itsk_objekte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Komponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Komponente',
                'verbose_name_plural': 'Komponente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Komponente_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Komponente_art',
                'verbose_name_plural': 'Komponente_art',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=120)),
                ('vorname', models.CharField(max_length=120)),
                ('geburtstag', models.DateField(blank=True, null=True)),
                ('bild', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedy', models.CharField(max_length=120, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remedy',
                'verbose_name_plural': 'Remedy',
                'ordering': ['remedy'],
            },
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(max_length=120, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rolle',
                'verbose_name_plural': 'Rolle',
                'ordering': ['rolle'],
            },
        ),
        migrations.CreateModel(
            name='Sap_system_landschaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sap_system_landschaft',
                'verbose_name_plural': 'Sap_system_landschaft',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standort', models.CharField(max_length=120)),
                ('strasse', models.CharField(max_length=120)),
                ('raum', models.CharField(max_length=120)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standort',
                'ordering': ['standort', 'strasse', 'raum'],
            },
        ),
        migrations.CreateModel(
            name='Verfahren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verfahren', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verfahren',
                'verbose_name_plural': 'Verfahren',
                'ordering': ['verfahren'],
            },
        ),
        migrations.CreateModel(
            name='Zt2t_ma2ro2ve2ko2re',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('t2t_komponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_org.komponente', verbose_name='Komponente')),
                ('t2t_mitarbeiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_org.mitarbeiter', verbose_name='Mitarbeiter')),
                ('t2t_remedy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_org.remedy', verbose_name='Remedy')),
                ('t2t_rolle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_org.rolle', verbose_name='Rolle')),
                ('t2t_verfahren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_org.verfahren', verbose_name='Verfahren')),
            ],
            options={
                'verbose_name': 'Zt2t_ma2ro2ve2ko2re',
                'verbose_name_plural': 'Zt2t_ma2ro2ve2ko2re',
                'ordering': ['t2t_mitarbeiter'],
            },
        ),
        migrations.AddField(
            model_name='komponente',
            name='komponente_art',
            field=models.ManyToManyField(to='app_org.Komponente_art'),
        ),
        migrations.CreateModel(
            name='Inventar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('inventar_art', models.ManyToManyField(to='app_org.Inventar_art')),
            ],
            options={
                'verbose_name': 'Inventar',
                'verbose_name_plural': 'Inventar',
                'ordering': ['name'],
            },
        ),
    ]
