# Generated by Django 3.2 on 2021-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=32)),
                ('vname', models.CharField(max_length=32)),
                ('geb', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField(default='2000-01-01')),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'ordering': ['id', 'nname', 'vname'],
            },
        ),
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField(default='2000-01-01')),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UserId',
                'verbose_name_plural': 'UserId',
                'ordering': ['id', 'uid'],
            },
        ),
    ]
