# Generated by Django 3.2 on 2021-08-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z_user2userid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(default='2099-12-31')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('t2t_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_core_user.user', verbose_name='User')),
                ('t2t_userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_core_user.userid', verbose_name='UserId')),
            ],
            options={
                'verbose_name': 'Z_user2userid',
                'verbose_name_plural': 'Z_user2userid',
                'ordering': ['id', 't2t_user', 't2t_userid'],
            },
        ),
    ]
