# Generated by Django 3.2 on 2021-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core_user', '0002_z_user2userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_user2userid',
            name='date_beg',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
